### ISSUE TITLE
mcubes casts ncalls to int type

### ISSUE THREAD

**Issue by dholladay00** [marcpaterno/gpuintegration#1]
Perhaps there are other parameters to modify before this one, but I think I would like to enable ncalls to go above 2e9 as increasing that parameter was resulting in lower error estimates reliably for my integrands. How much of a lift would it be to switch from casting to an int to casting to a `uint64_t` or other similar integral type? 

Or I am also open to other suggestions of integration function arguments to tweak to give similar reductions in the error estimates.

**Comment by marcpaterno** [comment]
The parameter `ncall` is a `double` for historical reasons (we are likely to change this in the future). `ncall` is used to calculate `ng`, in the line:
```
(int)pow(ncall / 2.0 + 0.25, 1.0 / ndim)
```
Assuming that `ndim` is not 1 (there are much better integration algorithms for 1-D integrals), then `ng` will not overflow an `int` unless `ncall` is very large. If `ndim==2` (the worst case), then `ncall` can go up to `2**65` before it overflows. So you should be able to use values greater than several billion (although the call will be slow).

We have just added a new demo (`mcubes/demo/one_hard_integrand.cu`) that allows one to play with setting `ncall` on the command line of the demo.

Please let us know if there is something else that makes it seem that large values of `ncall` are not showing the expected behavior.

**Comment by marcpaterno** [comment]
I’m going to close this issue as answered. Please re-open if you think there is something that needs to be done more immediately.
